[project]
name = "star"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "accessible-output2>=0.17",
    "argparse>=1.4.0",
    "audioop-lts>=0.2.2 ; python_full_version >= '3.13'",
    "boto3>=1.43.67",
    "configobj>=5.0.9",
    "google-cloud-texttospeech>=2.37.0",
    "mistune>=3.3.4",
    "platform-utils",
    "pydub>=0.25.1",
    "pyinstaller>=6.21.0",
    "resource-finder",
    "smart-list",
    "sound-lib",
    "websockets>=16.1.1",
    "accessible-wxpython-darkmode>=1.0.0",
    "wxpython>=4.2.5",
    "argon2-cffi>=25.1.0",
]

[tool.uv.sources]
platform-utils = { git = "https://github.com/accessibleapps/platform_utils" }
resource-finder = { git = "https://github.com/accessibleapps/resource_finder" }
smart-list = { git = "https://github.com/samtupy/smart_list_macos_fixes" }
accessible-wxpython-darkmode = { git = "https://github.com/alexoloopios/accessible-wxpython-darkmode" }
sound-lib = { git = "https://github.com/samtupy/sound_lib_macos_fixes" }
